Feat: 소셜로그인 구현
Kusitms-NumberOne/Backend pull request #16
Opened 2023-10-13 16:11 UTC by nohy6630

## 관련 이슈
close #10 

## 작업내용
- 네이버 로그인 api
![naver](https://github.com/Kusitms-NumberOne/Backend/assets/129354455/822da083-e382-4c9a-b132-003ccbb80bdd)
- 카카오 로그인 api
![kakao](https://github.com/Kusitms-NumberOne/Backend/assets/129354455/8945b46b-ba40-4909-b3d3-ef93f4fae115)
- jwt 토큰 이용한 시큐리티 인증
![test](https://github.com/Kusitms-NumberOne/Backend/assets/129354455/5a9b5b5c-d203-41e3-8c95-a1a4b1cce799)
- redis 이용한 refresh token 구현
![refresh](https://github.com/Kusitms-NumberOne/Backend/assets/129354455/309232d7-f518-4af2-8977-49012778045c)

## 참고사항
- application.yml을 수정되어 깃허브 시크릿 변경해야 함
- 로컬에서만 redis를 테스트 해봤는데 배포 이후에 docker-compose.yml에 맞게 redis가 ec2에서 잘 작동하는지 테스트 필요

2023-10-14 05:48 UTC, versatile0010 commented
고생해쓰 🔥🔥!  내일 리뷰하고 알려주께

2023-10-14 16:26 UTC, versatile0010 requested changes
코드 잘 보고 갑니다!!
전체적으로 깔끔하고, 보기 좋은 코드였던 것 같아요!

보면서 저도 많이 배우고 갑니다!
레디스 셋업도 제가 하려고 했는데.. 해주셔서 너무 감사드려요
+ 소셜 로그인 정말 고생하셨어요.. 

지금도 충분히 좋지만..
조금 더 개선될 수 있는 부분이 있어서
request changes 남겼습니다!

코멘트 남긴 부분, 적용하신 뒤에 다시 리뷰 요청주시면 좋을 것 같아요

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/entity/Token.java
> +
accessToken 을 이용해서 유저를 검색할 때, acessToken 에 인덱싱해서 쿼리 성능을 최적화하려고 한 시도가 아주 좋아보여요👍 실제로 쿼리가 인덱싱을 따라서 날라가는지 한번 확인해보면 좋을 것 같아요!!! 의도와는 조금 다를지도..?? 저도 한번 확인헤볼게요  😊

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/entity/Token.java
> +    }
`@setter` 를 닫아두고, 필요한 필드에 대해서 set 해야 하는 경우에만 따로 메서드로 작성한 게 정말 좋네요..
무심코 setter 을 열어놓거나, 혹은 setAccessToken 이라고 네이밍했을 수도 있을 것 같은데.. 프로젝트 규모가 커질수록 @Setter 는 약간의 리스크를 동반할 수 있다고 해요. (같은 프로젝트에 많은 개발 인원이 투입되는 경우)

영진님처럼 하면, 객체의 변화를 탐지하기 훨씬 수월해지죠.
디테일이 살아있네요!!! 🥹

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/service/TokenService.java
> +public class TokenService {
이 부분도 트랜잭션 관리를 위해서 `@Transactional(readOnly=true)` 옵션을 클래스에 두는 걸 추천해요!!

대신 db 에 wrtie 가 일어나는 로직에는 (별도로 메서드 단위로) `@Transactional` 을 달아두어야 합니다!

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/service/TokenService.java
> +        tokenRepository.save(token);//redis의 경우 jpa와 달리 transactional을 이용해도 데이터 수정시에 명시적으로 save를 해줘야 함
이 부분 놓치고 있었네요..

레디스에 대해서 배워갑니다 👍👍

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/config/auth/JwtFilter.java
> +    @Override
토큰의 형식이 유효하지 않으면 error response 가 어떻게 반환되나요??
가령, 시그니쳐가 다르다던가 조금 잘린 경우에는 어떻게 처리가 되는지 궁금합니다 !!! 🤔

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/member/entity/Member.java
> +@Getter
Table 의 이름을 명시해두는 건 어떨까요??
`@Table("MEMBER")` 등과 같이 프로젝트 내에서 통일하는 게 좋아보여요!!

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/member/entity/Member.java
> +    public Member(String email) {
정적 팩토리 메서드를 적용해보는 건 어떨까요??

나중에 Member 필드가 추가되는 경우에 조금 더 수월하게 작업할 수 있을 지 고려해보면 좋을 것 같아요! 👍

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/member/entity/Member.java
> +@NoArgsConstructor(access = AccessLevel.PROTECTED)
`@NoArgsConstructor(access = AccessLevel.PROTECTED)` 으로 
엔티티의 무분별한 생성을 방지한게 정말 좋았습니다.. 🥹

저는 이 부분 공부하면서,
그럼 왜 private 로 안하고 protected 으로 하는건지..? 에 대해서 의문을 많이 가졌었는데 혹시 영진님도 그러셨다면..
- jpa 의 프록시 객체에 대해서 서치해보면 좋을 것 같아요!

엔티티 코드 깔끔하네요 👍

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/service/TokenService.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 토큰"));
이 부분도 커스텀 예외로 처리하는게 어때요??
위처럼 구현하면, 
추후에 클라이언트에서, 예외 리스폰스에 대한 추가적인 요구사항이 생겼을 때 일일히 모두 다 찾아서 수정해야 하는 번거로움이 있을 수 있어요.
`com/numberone/backend/exception` 내에 작성된 코드를 활용해서 해결할 수 있을 듯 해요!!

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/service/TokenService.java
> +            String refreshToken = jwtUtil.createToken(email, 1000L * 60 * 30);//30분
토큰 유효 기간은 secret 으로 관리하는게 어떨까요??

2023-10-14 16:26 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/service/TokenService.java
> +        ResponseEntity<KakaoInfoResponse> response = restTemplate.exchange(kakaoProperties.getUser_api_url(), HttpMethod.GET, new HttpEntity<>(null, headers), KakaoInfoResponse.class);
`RestTemplate` 을 이용해서 api 통신을 구현한 점 좋은 것 같아요  👍

왠지 많은 시행착오와 어려움이 있었을 것 같은데..
깔끔하게 구현하는데 성공하셨네요..
멋집니다 👍🥹

추후에 `OpenFeign` 을 사용해서 RestTemplate 를 대체해보는 걸 구현해보면 좋을 것 같아요!! 훨씬 간단하답니다

이번 프로젝트에서는 그대로 가도 좋을 것 같아요!!

고생하셨어요 👍

2023-10-14 16:26 UTC, versatile0010 commented on docker-compose.yml
이 부분 저희 인프라 서버에서 잘 작동되는지 제가 확인해볼게요!!

2023-10-14 16:30 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 사용자입니다."));
이메일이 같은 유저에 대해서는 어떻게 예외 처리가 되나요??

2023-10-14 16:35 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/entity/Token.java
> +    private String email;
엔티티의 Primary key 를 정할 때는, 외부의 값에 의존하는 상황을 최대한 피해야한다고 생각해요.

물론 그럴일은 적겠지만, 유저로부터 email 을 더이상 받아오지 못하는 경우도 발생할 수 있을텐데..
만약 그렇게 된다면.. ( + 넘버원 서비스가 잘 운영되고 있다면 ) -> 엔티티의 pk 를 바꿔줘야 하는 아주 아주 번거롭고 무거운 작업이 필요할 수 있어요.. 😰

token 의 pk 는 auto increment 되는 Long id 로 정의해두는 것이 보다 안전할 것 같아요!!

2023-10-14 16:38 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/member/service/MemberService.java
> +@Service
아,, 참고로 @transactional 은 spring aop 를 기반으로 구현되기 때문에
private 메서드는 transaction 이 적용되지 않는다는 것을 주의해주세요!

2023-10-14 16:40 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/member/entity/Member.java
> +    public Member(String email) {
읽어보면 좋은 레퍼런스 하나 첨부합니다!!
https://tecoble.techcourse.co.kr/post/2020-05-26-static-factory-method/

2023-10-14 16:50 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/entity/Token.java
> +    private String email;
아.. redis key-value store 형태니까 
 email 이 key 값이 되고 token 이 value 가 되야 해서 그런건가요!?!?!?

2023-10-14 16:53 UTC, versatile0010 commented on src/main/java/com/numberone/backend/domain/token/service/TokenService.java
> +            String refreshToken = jwtUtil.createToken(email, 1000L * 60 * 30);//30분
헉 지금보니까 accessToken, refreshToken 의 생명주기가 서로 반대로 된 것 같아요!
refresh token 이 14일,
accessToken 이 30분이어야지 하지 않나요?? 😰

2023-10-14 17:00 UTC, versatile0010 commented on src/main/generated/com/numberone/backend/config/basetime/QBaseTimeEntity.java
> +
아!!! 혹시 git ignore 해도 q 클래스들이 git 에 자꾸 등록된다면
git 캐시를 clean 하는 게 방법이 될 수 있어요!!

2023-10-15 13:09 UTC, nohy6630 commented on src/main/java/com/numberone/backend/domain/member/service/MemberService.java
> +                .orElseThrow(() -> new IllegalArgumentException("존재하지 않는 사용자입니다."));
토큰을 발급할 때 소셜로그인을 통해 얻어온 이메일이 db에 존재하지 않을 때만 새로 유저를 등록했기에 이메일이 같은 유저는 없다고 생각하고 작성했습니다!

2023-10-15 13:17 UTC, nohy6630 commented on src/main/java/com/numberone/backend/domain/member/service/MemberService.java
> +@Service
평소에는 db 데이터를 가져와서 수정해야 하는 메서드같이 커넥션의 유지가 필요할 때만, 메서드 단위에 @Transactional 어노테이션을 사용했는데 아예 서비스 클래스 단위에 적용하는 거는 몰랐네요! 감사합니다! :)

2023-10-15 13:19 UTC, nohy6630 commented on src/main/java/com/numberone/backend/domain/token/entity/Token.java
> +
이 부분은 저도 실제로 인덱싱이 작동하는지 궁금하긴 했는데 확인해봐야 될것같아요! 감사합니다 :)

2023-10-15 13:22 UTC, nohy6630 commented on src/main/java/com/numberone/backend/domain/token/service/TokenService.java
> +            String refreshToken = jwtUtil.createToken(email, 1000L * 60 * 30);//30분
헉 그렇네요! ㅠㅠ 발견 감사합니다. 나중에 많이 헤맸을 것 같아요

2023-10-15 13:24 UTC, nohy6630 commented on src/main/java/com/numberone/backend/domain/token/service/TokenService.java
> +        ResponseEntity<KakaoInfoResponse> response = restTemplate.exchange(kakaoProperties.getUser_api_url(), HttpMethod.GET, new HttpEntity<>(null, headers), KakaoInfoResponse.class);
OpenFeign 코드도 봤었는데 저도 되게 간단하다고 생각이 들었습니다! 시간이 된다면 나중에 리팩토링 하고싶네요 ㅎㅎ

2023-10-15 13:48 UTC, nohy6630 commented on src/main/java/com/numberone/backend/domain/token/entity/Token.java
> +    private String email;
네 저도 재현님 리뷰 보면서 찾아봤는데 key-value형태다 보니 문자열형태의 id값을 직접 세팅해주는게 권장되는것 같더라구요.
그리고 redis 엔티티의 경우에는 일반적인 jpa엔티티 처럼 GeneratedValue로 아이디 값을 자동생성하는게 지원되지 않는 것 같았습니다. 그래서 직접 id를 세팅해줘야 하는데 유저의 정보를 고유하게 나타내는게 이메일이라 생각하여 이메일을 키로 하게 되었습니다!
https://hudi.blog/refresh-token-in-spring-boot-with-redis/

2023-10-15 15:30 UTC, versatile0010 approved these changes
고생하셨습니다!!

2023-10-15 15:36 UTC, merged